// Code generated by mockery v2.43.2. DO NOT EDIT.

package bcwatch

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockController is an autogenerated mock type for the Controller type
type MockController struct {
	mock.Mock
}

// WatchAttendanceRecorded provides a mock function with given fields:
func (_m *MockController) WatchAttendanceRecorded() func(context.Context) error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WatchAttendanceRecorded")
	}

	var r0 func(context.Context) error
	if rf, ok := ret.Get(0).(func() func(context.Context) error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(context.Context) error)
		}
	}

	return r0
}

// WatchAttendanceUpdated provides a mock function with given fields:
func (_m *MockController) WatchAttendanceUpdated() func(context.Context) error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WatchAttendanceUpdated")
	}

	var r0 func(context.Context) error
	if rf, ok := ret.Get(0).(func() func(context.Context) error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(context.Context) error)
		}
	}

	return r0
}

// NewMockController creates a new instance of MockController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockController {
	mock := &MockController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
