// Code generated by mockery v2.43.2. DO NOT EDIT.

package user

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/the-witcher-knight/timekeeper/internal/model"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *MockRepository) CreateUser(ctx context.Context, user model.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserByFilter provides a mock function with given fields: ctx, filters, lock
func (_m *MockRepository) GetUserByFilter(ctx context.Context, filters FilterInput, lock bool) (model.User, error) {
	ret := _m.Called(ctx, filters, lock)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByFilter")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, FilterInput, bool) (model.User, error)); ok {
		return rf(ctx, filters, lock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, FilterInput, bool) model.User); ok {
		r0 = rf(ctx, filters, lock)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, FilterInput, bool) error); ok {
		r1 = rf(ctx, filters, lock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
